---
apiVersion: v1
kind: Pod
metadata:
  name: wipeshared
spec:
  restartPolicy: "Never"
  volumes:
  - name: composer-card-store
    persistentVolumeClaim:
      claimName: composer-pvc
  - name: shared
    persistentVolumeClaim:
      claimName: shared-pvc
  - name: ledger
    persistentVolumeClaim:
      claimName: ledger-pvc
  containers:
  - name: wipeshared
    image: ibmblockchain/fabric-tools:1.0.3
    imagePullPolicy: Always
    command: ["sh", "-c", "rm -rf /shared/* /home/* /ledger/*"]
    volumeMounts:
    - name: composer-card-store
      mountPath: /home
    - name: shared
      mountPath: /shared
    - name: ledger
      mountPath: /ledger