---
# The service to expose composer rest server
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ibm-blockchain-composer.fullname" . }}-rest-server
  labels:
    app: {{ template "ibm-blockchain-composer.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    run: {{ template "ibm-blockchain-composer.fullname" . }}-rest-server
spec:
  type: NodePort
  selector:
    name: {{ template "ibm-blockchain-composer.fullname" . }}-rest-server
    app: {{ template "ibm-blockchain-composer.name" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 31090
    name: http
