---
# The service to expose composer playground
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ibm-blockchain-composer.fullname" . }}-playground
  labels:
    app: {{ template "ibm-blockchain-composer.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    run: {{ template "ibm-blockchain-composer.fullname" . }}-playground
spec:
  type: NodePort
  selector:
    name: {{ template "ibm-blockchain-composer.fullname" . }}-playground
    app: {{ template "ibm-blockchain-composer.name" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 31080
    name: http
