---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "ibm-blockchain-composer.fullname" . }}-rest-server
  labels:
    app: {{ template "ibm-blockchain-composer.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "ibm-blockchain-composer.fullname" . }}-rest-server
      labels:
        app: {{ template "ibm-blockchain-composer.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        name: {{ template "ibm-blockchain-composer.fullname" . }}-rest-server
    spec:
      volumes:
      - name: composer-card-store
        persistentVolumeClaim:
          claimName: {{ template "ibm-blockchain-composer-pvc.name" . }}
      containers:
      - name: composer-rest-server
        image: ibmblockchain/composer-rest-server:0.16.2
        imagePullPolicy: {{ .Values.blockchain.pullPolicy }}
        env:
        - name: COMPOSER_CARD
          value: {{ .Values.blockchain.composerRestServerCard }}
        - name: COMPOSER_NAMESPACES
          value: never
        volumeMounts:
        - name: composer-card-store
          mountPath: /home/composer/.composer
