---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "ibm-blockchain-composer.fullname" . }}-playground
  labels:
    app: {{ template "ibm-blockchain-composer.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "ibm-blockchain-composer.fullname" . }}-playground
      labels:
        app: {{ template "ibm-blockchain-composer.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        name: {{ template "ibm-blockchain-composer.fullname" . }}-playground
    spec:
      volumes:
      - name: {{ template "ibm-blockchain-shared-pvc.name" . }}
        persistentVolumeClaim:
         claimName: {{ template "ibm-blockchain-shared-pvc.name" . }}
      - name: composer-card-store
        persistentVolumeClaim:
          claimName: {{ template "ibm-blockchain-composer-pvc.name" . }}
      containers:
      - name: composer-playground
        image: hyperledger/composer-playground:0.16.0
        imagePullPolicy: {{ .Values.blockchain.pullPolicy }}
        volumeMounts:
        - name: composer-card-store
          mountPath: /home/composer/.composer
